### ISSUE TITLE
Trying to use the sidekick on a page that uses Spectrum Web Components results in errors

### ISSUE THREAD

**Issue by dylandepass** [adobe/aem-sidekick#176]
Happens on both
https://main--rosalind-boilerplate--dylandepass.hlx.page/tools/sidekick/library.html?plugin=blocks

and 

https://rum-admin--helix-website--adobe.aem.live/tools/rum/admin/orgs.html

```
polyfills.min.js:35 DOMException: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
    at Nt.Element.attachShadow (chrome-extension://iijidanmjddcjacejcjofhcjmgkkiijo/polyfills.min.js:9:13919)
    at new rt (chrome-extension://iijidanmjddcjacejcjofhcjmgkkiijo/index.js:41:41963)
    at N (chrome-extension://iijidanmjddcjacejcjofhcjmgkkiijo/polyfills.min.js:9:4526)
    at o (chrome-extension://iijidanmjddcjacejcjofhcjmgkkiijo/polyfills.min.js:9:3804)
    at m (chrome-extension://iijidanmjddcjacejcjofhcjmgkkiijo/polyfills.min.js:9:4320)
    at Document.importNode (chrome-extension://iijidanmjddcjacejcjofhcjmgkkiijo/polyfills.min.js:9:11603)
    at o2.u (chrome-extension://iijidanmjddcjacejcjofhcjmgkkiijo/index.js:153:3417)
    at oy.$ (chrome-extension://iijidanmjddcjacejcjofhcjmgkkiijo/index.js:153:5028)
    at oy._$AI (chrome-extension://iijidanmjddcjacejcjofhcjmgkkiijo/index.js:153:4512)
    at c2 (chrome-extension://iijidanmjddcjacejcjofhcjmgkkiijo/index.js:153:7690)
 ```

**Comment by rofe** [comment]
Fixed in #197
